name: second_brain
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.2.4+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.5
  get_storage: ^2.1.1
#  time_planner: ^0.1.2+1
  intl:
  windows_notification: ^1.3.0
  path_provider: ^2.1.4

  window_manager: ^0.4.0
  flutter_heatmap_calendar: ^1.0.5
  iconsax: ^0.0.8
  delightful_toast: ^1.1.0
#  audioplayers: ^6.0.0
  lottie: ^3.1.2

  flutter_expandable_fab: ^2.2.0
  timeline_tile: ^2.0.0
  easy_sidemenu: ^0.6.0
  equatable: ^2.0.5
#  provider: ^6.1.2
  flutter_mobx: ^2.0.6+5
  freezed: ^2.3.2
  infinite_scroll_pagination: ^4.0.0
  flutter_staggered_animations: ^1.1.1
  pull_down_button: ^0.10.1
  flutter_slidable: ^3.1.1

  change_app_package_name: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/animations/
    - assets/lottie/
    - assets/sounds/
    - assets/sounds/success.mp3
    - assets/sounds/error.mp3
