name: second_brain

description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.4+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  flutter_heatmap_calendar: ^1.0.5
  gradient_circular_progress_indicator: ^0.0.4
  iconsax_plus: ^1.0.0

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Utilities
  bitsdojo_window: ^0.1.6
  delightful_toast: ^1.1.0
  intl:
  launch_at_startup: ^0.3.1
  package_info_plus: ^8.0.2
  system_tray: ^2.0.3
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  windows_notification: ^1.3.0
  flutter_lints: ^2.0.0
  elegant_notification: ^2.3.0
#  cherry_toast: ^1.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/animations/
    - assets/lottie/
    - assets/sounds/
    - assets/sounds/bite.mp3
    - assets/sounds/error.mp3
    - assets/sounds/clock-alarm.mp3
    - assets/sounds/timesup.mp3