// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// // import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBlNJIWINilRLimystLXeKMOJwRfLUFqOo',
//     appId: '1:467031075305:web:99724f7dec4d1b18304378',
//     messagingSenderId: '467031075305',
//     projectId: 'al-maafer',
//     authDomain: 'al-maafer.firebaseapp.com',
//     storageBucket: 'al-maafer.appspot.com',
//     measurementId: 'G-2X0W1SSGMN',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCDWmBK6e-Z81je8LJyemERZ5BJHkdGQc8',
//     appId: '1:467031075305:android:2c21a0d12bc9c008304378',
//     messagingSenderId: '467031075305',
//     projectId: 'al-maafer',
//     storageBucket: 'al-maafer.appspot.com',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBlNJIWINilRLimystLXeKMOJwRfLUFqOo',
//     appId: '1:467031075305:web:c7968f11076a6458304378',
//     messagingSenderId: '467031075305',
//     projectId: 'al-maafer',
//     authDomain: 'al-maafer.firebaseapp.com',
//     storageBucket: 'al-maafer.appspot.com',
//     measurementId: 'G-K6TTLC665R',
//   );
//
// }